In [1]:
import numpy as np


In [2]:
np.array(["harish",4 ,6])

array(['harish', '4', '6'], dtype='<U11')

In [3]:
np.array([12,3,1,2,4,5,8])[-5:-1]

array([1, 2, 4, 5])

In [12]:
np.array([[2,3],[3,4]])

array([[2, 3],
       [3, 4]])

In [5]:
a = np.array([3,4])

In [6]:
a

array([3, 4])

In [19]:
b = np.arange(15)

In [21]:
b.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [23]:
b = b.reshape(5,3)

In [24]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [29]:
type(np.array(["harish",4 ,6]))

numpy.ndarray

In [27]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
a = np.array([[1,2,3,4],[6,7,4,1]], ndmin = 3)

In [32]:
a

array([[[1, 2, 3, 4],
        [6, 7, 4, 1]]])

In [33]:
a1  = np.array([1,2,3], ndmin = 5, dtype = int)

In [34]:
a1

array([[[[[1, 2, 3]]]]])

In [35]:
x = np.array([(1,2),(4,5)], dtype = [("a","<i2"),("b", "<i8")])

In [36]:
x

array([(1, 2), (4, 5)], dtype=[('a', '<i2'), ('b', '<i8')])

In [37]:
x[0][0]

1

In [38]:
x[1][1]

5

In [39]:
x[0][1]

2

In [40]:
type(x[1][0])

numpy.int16

In [41]:
type(x[0][0])

numpy.int16

In [42]:
type(x[0][1])

numpy.int64

In [43]:
x1 = np.array([(11,2),(4,5)], dtype = [("a","<i8"),("b", "<i8")])

In [80]:
type(x1[0][0])

numpy.int64

In [44]:
y =np.mat(x1)

In [45]:
y

matrix([[(11, 2), ( 4, 5)]], dtype=[('a', '<i8'), ('b', '<i8')])

In [46]:
np.mat([[1,4],[3,2,1]])

C:\Users\Harish Sharma\anaconda3\lib\site-packages\numpy\matrixlib\defmatrix.py:145: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = N.array(data, dtype=dtype, copy=copy)


matrix([[list([1, 4]), list([3, 2, 1])]], dtype=object)

In [89]:
#numpy asarray

In [90]:
a = [1,2,3]

In [91]:
type(a)

list

In [92]:
type(np.asarray(a))

numpy.ndarray

In [93]:
np.asarray((1,2))

array([1, 2])

In [47]:
issubclass(np.matrix, np.ndarray)

True

In [104]:
#asanyarray

In [113]:
a = [1,2]
np.asanyarray(a)

array([1, 2])

In [115]:
type(np.asanyarray(a))

numpy.ndarray

In [116]:
#Deep copy and shallow copy

In [117]:
x = np.array([1,2,3,4])

In [118]:
y = x

In [119]:
y

array([1, 2, 3, 4])

In [120]:
y[1]

2

In [121]:
x[1]

2

In [122]:
y[1] = 50

In [128]:
x

array([ 1, 50,  3,  4])

In [124]:
x[1]

50

In [126]:
z = np.copy(x)

In [127]:
z

array([ 1, 50,  3,  4])

In [130]:
z[1]

50

In [131]:
z[0] = 45

In [132]:
z

array([45, 50,  3,  4])

In [133]:
y

array([ 1, 50,  3,  4])

In [134]:
x

array([ 1, 50,  3,  4])

In [135]:
#Numpy.fromfuction

In [142]:
np.fromfunction(lambda i,j:i ==j, (3,3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [48]:
np.fromfunction(lambda i,j: i!=j, (3,3), dtype=int)

array([[False,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [164]:
np.fromfunction(lambda i,j,k,l:i*j*k*l,(2,3,3,3), dtype=int)

array([[[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]],


       [[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 1, 2],
         [0, 2, 4]],

        [[0, 0, 0],
         [0, 2, 4],
         [0, 4, 8]]]])

In [56]:
np.fromfunction(lambda i,j,k: i+j+k, (2,2,3),dtype=complex)

array([[[0.+0.j, 1.+0.j, 2.+0.j],
        [1.+0.j, 2.+0.j, 3.+0.j]],

       [[1.+0.j, 2.+0.j, 3.+0.j],
        [2.+0.j, 3.+0.j, 4.+0.j]]])

In [59]:
np.fromfunction(lambda i,j,k: i+j-k, (2,2,3),dtype=int)

array([[[ 0, -1, -2],
        [ 1,  0, -1]],

       [[ 1,  0, -1],
        [ 2,  1,  0]]])

In [179]:
iterable = [x*x for x in range(5)]

In [180]:
iterable

[0, 1, 4, 9, 16]

In [61]:
iter = [x**x for x in range(5)]

In [62]:
iter

[1, 1, 4, 27, 256]

In [66]:
item = [x*4 for x in range(6)]
item

[0, 4, 8, 12, 16, 20]

In [68]:
item = [x+3 for x in range(10)]
item

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [190]:
a = np.fromiter(iterable, int)

In [189]:
a

[array([ 0,  1,  4,  9, 16])]

In [72]:
b = np.fromstring("214 435", sep=" ")
b

array([214., 435.])

In [78]:
b = np.fromstring("400 200 100", sep=" ")
b

array([400., 200., 100.])

In [70]:
b1 = np.fromstring("12  24", sep= " ")

In [71]:
b1

array([12., 24.])

In [202]:
#datatype conversion

In [203]:
mylist = [1,2,3,4]
import numpy as np
arr = np.array(mylist)
print("type/class of the object:",type(arr))

type/class of the object: <class 'numpy.ndarray'>


In [204]:
print(arr)

[1 2 3 4]


In [206]:
mymat = [[1,2,3],[1,4,7],[3,6,9]]

In [207]:
mat = np.array(mymat)
print("type/class of this object:", type(mat))

type/class of this object: <class 'numpy.ndarray'>


In [210]:
print("here is the matrix\n-", mat, "\n------")
print(mat)

here is the matrix
- [[1 2 3]
 [1 4 7]
 [3 6 9]] 
------
[[1 2 3]
 [1 4 7]
 [3 6 9]]


In [211]:
#arange and linspace

In [216]:
list(range(1,21,4))

[1, 5, 9, 13, 17]

In [101]:
a =list(range(-10,10))

In [102]:
a

[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [121]:
a1 = list(range(10,2,-2))

In [122]:
a1

[10, 8, 6, 4]

In [220]:
list(np.arange(1,20,1.2))

[1.0,
 2.2,
 3.4000000000000004,
 4.6000000000000005,
 5.800000000000001,
 7.000000000000001,
 8.200000000000001,
 9.400000000000002,
 10.600000000000001,
 11.8,
 13.000000000000002,
 14.200000000000003,
 15.400000000000002,
 16.6,
 17.800000000000004,
 19.000000000000004]

In [222]:
np.arange(2.1,25,2.5)

array([ 2.1,  4.6,  7.1,  9.6, 12.1, 14.6, 17.1, 19.6, 22.1, 24.6])

In [225]:
np.arange(25,.5,-2.1)

array([25. , 22.9, 20.8, 18.7, 16.6, 14.5, 12.4, 10.3,  8.2,  6.1,  4. ,
        1.9])

In [229]:
np.arange(1,2,.5)

array([1. , 1.5])

In [233]:
[(np.linspace(1,25,15))]

[array([ 1.        ,  2.71428571,  4.42857143,  6.14285714,  7.85714286,
         9.57142857, 11.28571429, 13.        , 14.71428571, 16.42857143,
        18.14285714, 19.85714286, 21.57142857, 23.28571429, 25.        ])]

In [237]:
l = "harish"

In [239]:
l.title()

'Harish'

In [255]:
(np.ones((4,4)))*41

array([[41., 41., 41., 41.],
       [41., 41., 41., 41.],
       [41., 41., 41., 41.],
       [41., 41., 41., 41.]])

In [257]:
np.empty((2,4))*0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [260]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [268]:
np.logspace(4,30, num=28)


array([1.00000000e+04, 9.18254284e+04, 8.43190929e+05, 7.74263683e+06,
       7.10970943e+07, 6.52852114e+08, 5.99484250e+09, 5.50478981e+10,
       5.05479682e+11, 4.64158883e+12, 4.26215883e+13, 3.91374560e+14,
       3.59381366e+15, 3.30003479e+16, 3.03027108e+17, 2.78255940e+18,
       2.55509709e+19, 2.34622885e+20, 2.15443469e+21, 1.97831888e+22,
       1.81659979e+23, 1.66810054e+24, 1.53174046e+25, 1.40652724e+26,
       1.29154967e+27, 1.18597101e+28, 1.08902296e+29, 1.00000000e+30])

In [269]:
l = [1,2,3,4,5,6]
np.matrix(l)

matrix([[1, 2, 3, 4, 5, 6]])

In [272]:
 k =(np.ones((3,4,8))) + 5

In [274]:
k*2

array([[[12., 12., 12., 12., 12., 12., 12., 12.],
        [12., 12., 12., 12., 12., 12., 12., 12.],
        [12., 12., 12., 12., 12., 12., 12., 12.],
        [12., 12., 12., 12., 12., 12., 12., 12.]],

       [[12., 12., 12., 12., 12., 12., 12., 12.],
        [12., 12., 12., 12., 12., 12., 12., 12.],
        [12., 12., 12., 12., 12., 12., 12., 12.],
        [12., 12., 12., 12., 12., 12., 12., 12.]],

       [[12., 12., 12., 12., 12., 12., 12., 12.],
        [12., 12., 12., 12., 12., 12., 12., 12.],
        [12., 12., 12., 12., 12., 12., 12., 12.],
        [12., 12., 12., 12., 12., 12., 12., 12.]]])

In [280]:
x1 = np.ones((3,3))

In [283]:
x2 = np.zeros((3,3))

In [284]:
y = x1+x1

In [285]:
y

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [293]:
u = np.arange(4,8)

In [294]:
u

array([4, 5, 6, 7])

In [295]:
u1 = np.linspace(4,8,80)

In [296]:
u1

array([4.        , 4.05063291, 4.10126582, 4.15189873, 4.20253165,
       4.25316456, 4.30379747, 4.35443038, 4.40506329, 4.4556962 ,
       4.50632911, 4.55696203, 4.60759494, 4.65822785, 4.70886076,
       4.75949367, 4.81012658, 4.86075949, 4.91139241, 4.96202532,
       5.01265823, 5.06329114, 5.11392405, 5.16455696, 5.21518987,
       5.26582278, 5.3164557 , 5.36708861, 5.41772152, 5.46835443,
       5.51898734, 5.56962025, 5.62025316, 5.67088608, 5.72151899,
       5.7721519 , 5.82278481, 5.87341772, 5.92405063, 5.97468354,
       6.02531646, 6.07594937, 6.12658228, 6.17721519, 6.2278481 ,
       6.27848101, 6.32911392, 6.37974684, 6.43037975, 6.48101266,
       6.53164557, 6.58227848, 6.63291139, 6.6835443 , 6.73417722,
       6.78481013, 6.83544304, 6.88607595, 6.93670886, 6.98734177,
       7.03797468, 7.08860759, 7.13924051, 7.18987342, 7.24050633,
       7.29113924, 7.34177215, 7.39240506, 7.44303797, 7.49367089,
       7.5443038 , 7.59493671, 7.64556962, 7.69620253, 7.74683

In [307]:
x = np.arange(16)

In [308]:
x.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [309]:
x.reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [310]:
x.reshape(8,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [311]:
x.reshape(2,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [319]:
x.reshape((-4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [336]:
x1 = np.arange(12)
#np.diag(x1,0)

In [341]:
x2 =x1.reshape(3,4)

In [351]:
l = "harish"

In [352]:
l.title()

'Harish'

In [361]:
s =np.random.randint(4,16,15)

In [362]:
for i in s:
    print(i)

10
8
4
9
15
14
13
11
12
10
7
9
5
5
7
